import json
from pathlib import Path

ROOT = Path("/Users/hanjiho/Documents/감정평가사 기출문제")
TAXONOMY_PATH = ROOT / "taxonomy_v4.json"
PRACTICE_DIR = ROOT / "viewer/public/data/practice/civil-law"

with open(TAXONOMY_PATH, "r", encoding="utf-8") as f:
    tax = json.load(f)

civil = tax["민법"]["subjects"]["물권법"]

# Let's map sections and items to expected practice json file names.
# In practice_to_app.py:
# sub_subj, ch, sec, it = map_civil_taxonomy(sub_subj, ch, sec, it)
# We can search civil-gen-*.json filenames to see which ones are present.

files = [f.name for f in PRACTICE_DIR.glob("*.json")]
print(f"Total practice files in civil-law: {len(files)}")

# Let's look at the mapping logic in practice_to_app.py.
# Actually, the file names generated by the generator scripts are like:
# civil-gen-ch10-sec06-item03.json
# Let's analyze how many items there are in 물권법.
for chapter in civil:
    ch_name = chapter["name"]
    for section in chapter["sections"]:
        sec_name = section["name"]
        items = section.get("items", [])
        if not items:
            # If no items, it's just a section level topic.
            print(f"[Section-level] {ch_name} > {sec_name}")
        else:
            for item in items:
                item_name = item["name"]
                print(f"[Item-level] {ch_name} > {sec_name} > {item_name}")
